# Generated by Django 5.2.3 on 2025-06-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="purchase_price",
            new_name="price",
        ),
    ]
