# Generated by Django 5.2.3 on 2025-07-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_rename_purchase_price_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(default=True, verbose_name="В наличии"),
        ),
    ]
